import subprocess
process1=subprocess.run(['yasm','-f','bin','code/boot.asm','-o','boot.bin'],capture_output=True,text=True)
print(process1.stdout)
print(process1.stderr)


process2=subprocess.run(['yasm','-f','bin','code/kernel.asm','-o','kernel.bin'],capture_output=True,text=True)
print(process2.stdout)
print(process2.stderr)
#process3=subprocess.run(['yasm','-f','bin','code/hello.asm','-o','hello.bin'],capture_output=True,text=True)
#print(process3.stdout)
#print(process3.stderr)
#process4=subprocess.run(['yasm','-f','bin','shel.asm','-o','shel.bin'],capture_output=True,text=True)
#print(process4.stdout)
#print(process4.stderr)
#process5=subprocess.run(['yasm','-f','bin','booth.asm','-o','booth.bin'],capture_output=True,text=True)
#print(process5.stdout)
#print(process5.stderr)
#print("gcc пошел")
#proc_gcc=subprocess.run(['i686-elf-gcc','-ffreestanding','-O0','-nostdlib','-fno-stack-protector','-m32','-c','code/kernel.c','-o','kernel_main.o'],capture_output=True,text=True)
#print(proc_gcc.stdout)
#print(proc_gcc.stderr)
#print("собираем .о файл в elf")
#proc_ld=subprocess.run(['i686-elf-ld','-o','kernel.elf','-Ttext=0x7E000','kernel.o','kernel_main.o'],capture_output=True,text=True)
#print(proc_ld.stdout)
#print(proc_ld.stderr)
#print("собираем бинарник ")
#proc_link=subprocess.run(['objcopy','-O','binary','kernel_main.0','cpart.bin'],capture_output=True,text=True)
#print(proc_link.stderr)
#print(proc_link.stdout)

print("запись на дискету")
dd_zero=subprocess.run(['dd','if=/dev/zero','of=delta.img','bs=512','count=2880'])
print(dd_zero.stdout)
print(dd_zero.stderr)
dd_start1=subprocess.run(['dd','if=boot.bin','of=delta.img','bs=512','conv=notrunc'],capture_output=True,text=True)
print(dd_start1.stdout)
print(dd_start1.stderr)
dd_start2=subprocess.run(['dd','if=kernel.bin','of=delta.img','bs=512','seek=1','conv=notrunc'],capture_output=True,text=True)
print(dd_start2.stdout)
print(dd_start2.stderr)
#dd_flopy2=subprocess.run(['dd','if=/dev/zero','of=app.img','bs=512','count=2880'])
#print(dd_flopy2.stdout)
#print(dd_flopy2.stderr)
#dd_app1=subprocess.run(['dd','if=hello.bin','of=app.img','bs=512','conv=notrunc'],capture_output=True,text=True)
#print(dd_app1.stdout)
#print(dd_app1.stderr)
#dd_hdd=subprocess.run(['dd','if=/dev/zero','of=c.hdd','bs=1M','count=10'])
#print(dd_hdd.stdout)
#print(dd_hdd.stderr)
#dd_start5=subprocess.run(['dd','if=hello.bin','of=neko.img','bs=512','seek=8','conv=notrunc'],capture_output=True,text=True)
#print(dd_start5.stdout)
#print(dd_start5.stderr)
#dd_start3=subprocess.run(['dd','if=prog1.bin','of=faton.img','bs=512','seek=3','conv=notrunc'],capture_output=True,text=True)
#print(dd_start3.stdout)
#print(dd_start3.stderr)
#dd_start4=subprocess.run(['dd','if=shel.bin','of=faton.img','bs=512','seek=4','conv=notrunc'],capture_output=True,text=True)
#print(dd_start4.stdout)
#print(dd_start4.stderr)
#tf=input("start qemu y/n \n")
#if tf=="y":
#    qemu_start=subprocess.run(['qemu-system-i386 -fda neko.img -fdb app.img -hda c.hdd -boot a'],capture_output=True,text=True,shell=True)
#    print(qemu_start.stdout)
#    print(qemu_start.stderr)
#else:
#    print("close")
# /sbin/modprobe -r kvm_amd
# команда для рут прав что бы одыкватно работать с виртуалкой
